### PR TITLE
Added navbar

### PR DESCRIPTION
**Pull request by Voxargenteae**
Added a navbar to the top of the page. Currently has two options: "Home", which leads to the home page and "Discord server", which leads to the osu!lv server invite link

### CODE REVIEW

**Comment by jurrrgis** [comment]
We need a nice latvian/osu! related color scheme across the whole page!
I LOVE the base color you picked! ❤️
Please do yourself a favor and Google how to generate one, as a completely white background looks REALLY out of place (a white accent tone would be cool) at the moment.
Another NECCESARY thing without which I won't approve your PR with is having rounded corners are the bottom corners of the navbar, to make it look neat!

An optional thing you can do is make the navbar span across the whole viewport - by that I mean, keep the current button location, just "extend" it with a different color, if you know what I mean.
If you don't get what I mean ask HERE and not in Discord.

If you fix all of this, mark this issue as Pending if possible and do a new commit on the same branch!
I'll get back to you when I can - I won't go easy on you. :)

**Comment by Voxargenteae** [comment]
> We need a nice latvian/osu! related color scheme across the whole page! I LOVE the base color you picked! ❤️ Please do yourself a favor and Google how to generate one, as a completely white background looks REALLY out of place (a white accent tone would be cool) at the moment. Another NECCESARY thing without which I won't approve your PR with is having rounded corners are the bottom corners of the navbar, to make it look neat!
> 
> An optional thing you can do is make the navbar span across the whole viewport - by that I mean, keep the current button location, just "extend" it with a different color, if you know what I mean. If you don't get what I mean ask HERE and not in Discord.
> 
> If you fix all of this, mark this issue as Pending if possible and do a new commit on the same branch! I'll get back to you when I can - I won't go easy on you. :)

Rounded the bottom corners of the navbar and added a darker red background colour.

**Comment by TheStalwart** [comment]
1. Some code indentation is no bueno.
2. "Home" url should be relative, otherwise when testing locally link redirects to production environment.

Gonna fix both problems after merge, because YOLO

**Comment by jurrrgis** [comment]
I really dislike the choice of BG color, it should be white/red-ish, something close to latvian flag colors.
Anyhow, I am going on a break for holidays, however - do not expect me to let this slide if you decide to let me be a "required" reviewer for this project.

Up to you.

**Comment by Voxargenteae** [comment]
> I really dislike the choice of BG color, it should be white/red-ish, something close to latvian flag colors. Anyhow, I am going on a break for holidays, however - do not expect me to let this slide if you decide to let me be a "required" reviewer for this project.
> 
> Up to you.

Feel free to change the colour to whatever you feel is more appropriate yourself

**Pull request merged**
